name: priority_donor_club
description: A Flutter app for Priority Donor Club - blood donation with Uber-style tracking.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.2
  google_sign_in: ^5.4.2
  location: ^4.4.0
  provider: ^6.0.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
